repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    -   id: flake8
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.2.3
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-docstring-first
#     -   id: debug-statements
#     -   id: name-tests-test
#     -   id: double-quote-string-fixer
#     -   id: requirements-txt-fixer
#     -   id: name-tests-test
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: v1.4.3
#     hooks:
#     -   id: autopep8
# -   repo: https://github.com/pre-commit/pre-commit
#     rev: v1.14.2
#     hooks:
#     -   id: validate_manifest
# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v1.3.5
#     hooks:
#     -   id: reorder-python-imports
#         language_version: python3
# -   repo: https://github.com/asottile/pyupgrade
#     rev: v1.11.1
#     hooks:
#     -   id: pyupgrade
